-- Analytical queries against terminal.db (regenerated by build_db.py on every
-- data refresh). Run:  sqlite3 terminal.db < sql/queries.sql

-- 1. Top-quartile ROE within each sector (window function: NTILE)
SELECT sector, ticker, roe
FROM (SELECT sector, ticker, roe,
             NTILE(4) OVER (PARTITION BY sector ORDER BY roe DESC) AS quartile
      FROM companies WHERE roe IS NOT NULL)
WHERE quartile = 1
ORDER BY sector, roe DESC;

-- 2. Sector profile: size, average growth and profitability (sectors with 5+ names)
SELECT sector, COUNT(*) AS n,
       ROUND(AVG(revGrowth), 1) AS avg_rev_growth,
       ROUND(AVG(netMargin), 1) AS avg_net_margin
FROM companies
GROUP BY sector HAVING COUNT(*) >= 5
ORDER BY avg_net_margin DESC;

-- 3. Double-confirmation screen: names where BOTH the sector-relative implied
--    valuation and analyst consensus see >10% upside
SELECT ticker, name, price, impliedUpside, upside
FROM companies
WHERE impliedUpside > 10 AND upside > 10
ORDER BY impliedUpside + upside DESC
LIMIT 10;

-- 4. Three best FCF-margin names per sector (window function: RANK)
SELECT sector, ticker, fcfMargin
FROM (SELECT sector, ticker, fcfMargin,
             RANK() OVER (PARTITION BY sector ORDER BY fcfMargin DESC) AS rnk
      FROM companies WHERE fcfMargin IS NOT NULL)
WHERE rnk <= 3
ORDER BY sector, rnk;

-- 5. Value-vs-quality quadrants: how does analyst upside distribute when the
--    universe is bucketed by valuation (PEG) and quality (ROE)?
SELECT CASE WHEN peg < 2 THEN 'PEG < 2' ELSE 'PEG >= 2' END AS valuation,
       CASE WHEN roe >= 15 THEN 'ROE >= 15%' ELSE 'ROE < 15%' END AS quality,
       COUNT(*) AS n,
       ROUND(AVG(upside), 1) AS avg_analyst_upside
FROM companies
WHERE peg IS NOT NULL AND roe IS NOT NULL
GROUP BY 1, 2
ORDER BY n DESC;
